controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /index
    controller: App\Controller\IndexController::index

search_page:
    path: /search-page
    controller: App\Controller\IndexController::search

tag_cloud_component:
    path: /tag-cloud
    controller: App\Controller\TagCloudController::tagCloud
